### PR TITLE
added support for TypeScript

### PR DESCRIPTION
**Pull request by carlosrivera**
### TypeScript Support 
- Main file remains intact.
- Added types for `read()`: `src/index.d.ts`
- Type testing with **tsd**: `test/index.test-d.ts`
- `index.d.ts` copying to `dist` on `npm run build` 

#### 2 new dev-dependencies are needed:
- `types/node` and `tsd`, required only for testing.
_______
✅ npm run test 
✅ npm pack

### CODE REVIEW

**Comment by alexbbt** [comment]
This is pretty cool, I will do some testing locally with it, but it looks good. Do you know why the tsconfig.json is empty?

**Comment by carlosrivera** [comment]
> Do you know why the tsconfig.json is empty?

Oops! I touched the file but used tsd default config for testing.

**Comment by alexbbt** [comment]
@carlosrivera I have added a change that includes the type tests in the main test suite. Please update the types tests to pass.

**Comment by EvanHahn-Signal** [comment]
I would love to see this change merged. Please let me know if I can make a pull request based on this one to finish it off—I'm happy to do the work.

**Comment by alexbbt** [comment]
@EvanHahn-Signal Feel free to branch off of this PR and make your own. I only ask that you keep the commit history of the original branch so that the author can get credit

**Comment by EvanHahn-Signal** [comment]
Done in #28.

**Comment by alexbbt** [comment]
Merged via #28

**Pull request merged**
